/**
 * Dev seed: the 15 Kigali places, 6 users (1 admin, 3 drivers with vehicles and trips for
 * tomorrow, 2 passengers), one completed booking ready to rate and one pending request.
 * Trips are placed relative to "now" so a fresh seed always has tomorrow's trips.
 */
import {
  KIGALI_PLACES,
  addDays,
  buildCorridor,
  computeContribution,
  kigaliDateTime,
  kigaliDayKey,
  type DevAccount,
  type Weekday,
} from '@tmh/shared';
import type { Prisma } from '@prisma/client';
import fs from 'node:fs/promises';
import path from 'node:path';
import { prisma } from './db';
import { env } from './env';
import { occurrencesFor } from './services/trips';

/** A mock national ID scan for the admin verification queue. */
async function writeSampleId(): Promise<string> {
  const name = 'sample-id-jean-paul.svg';
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400" viewBox="0 0 640 400">
  <rect width="640" height="400" rx="24" fill="#EDEFFF"/><rect x="24" y="24" width="592" height="64" rx="12" fill="#4353FF"/>
  <text x="48" y="66" font-family="Arial" font-size="26" font-weight="700" fill="#fff">REPUBULIKA Y'U RWANDA · NATIONAL ID (SAMPLE)</text>
  <rect x="48" y="120" width="160" height="200" rx="12" fill="#C9CEF5"/><circle cx="128" cy="190" r="40" fill="#8E97E8"/><rect x="78" y="244" width="100" height="56" rx="28" fill="#8E97E8"/>
  <text x="240" y="150" font-family="Arial" font-size="22" fill="#191C2B">Names: HABIMANA Jean-Paul</text>
  <text x="240" y="190" font-family="Arial" font-size="22" fill="#191C2B">Date of birth: 14/03/1990</text>
  <text x="240" y="230" font-family="Arial" font-size="22" fill="#191C2B">Sex: M · Place of issue: Gasabo</text>
  <text x="240" y="270" font-family="Arial" font-size="22" fill="#191C2B">ID No: 1 1990 8 0012345 0 12</text>
  <text x="48" y="370" font-family="Arial" font-size="16" fill="#5B6178">Mock document generated by the dev seed — not a real ID.</text></svg>`;
  await fs.mkdir(env.uploadsDir, { recursive: true });
  await fs.writeFile(path.join(env.uploadsDir, name), svg);
  return name;
}

export const SEED_PHONES = {
  admin: '+250788000001',
  claudine: '+250788000002',
  aline: '+250788000003',
  jeanPaul: '+250788000004',
  grace: '+250788000005',
  eric: '+250788000006',
} as const;

export const DEV_ACCOUNTS: DevAccount[] = [
  { phone: SEED_PHONES.claudine, name: 'Claudine Uwimana', role: 'driver', note: 'Nyamirambo → CBD via Kimisagara & Nyabugogo, tomorrow 07:00 · 1 pending request' },
  { phone: SEED_PHONES.aline, name: 'Aline Mukamana', role: 'driver', note: 'Kanombe → CBD, women-only, Toyota RAV4, tomorrow 07:15' },
  { phone: SEED_PHONES.jeanPaul, name: 'Jean-Paul Habimana', role: 'driver', note: 'Remera → Kacyiru, EV Hyundai Kona, weekdays 08:00 · passenger to rate' },
  { phone: SEED_PHONES.grace, name: 'Grace Ingabire', role: 'passenger', note: 'Woman passenger with a trusted contact · pending request on Claudine’s trip' },
  { phone: SEED_PHONES.eric, name: 'Eric Nshuti', role: 'passenger', note: 'Completed ride with Jean-Paul, ready to rate' },
  { phone: SEED_PHONES.admin, name: 'Take Me Home Admin', role: 'admin', note: 'Use on the admin dashboard (localhost:5173)' },
];

const WEEKDAYS: Weekday[] = ['MO', 'TU', 'WE', 'TH', 'FR'];

async function createTrip(data: {
  driverId: string;
  vehicleId: string;
  departureTime: Date;
  stops: string[];
  seats: number;
  womenOnly?: boolean;
  isEV?: boolean;
  recurringDays?: Weekday[];
  seriesId?: string;
  status?: 'published' | 'completed';
}) {
  const corridor = buildCorridor(data.stops);
  return prisma.trip.create({
    data: {
      driverId: data.driverId,
      vehicleId: data.vehicleId,
      departureTime: data.departureTime,
      seriesId: data.seriesId,
      recurringDays: data.recurringDays as Prisma.InputJsonValue | undefined,
      seatsOffered: data.seats,
      womenOnly: data.womenOnly ?? false,
      isEV: data.isEV ?? false,
      totalKm: corridor[corridor.length - 1]!.cumulativeKm,
      status: data.status ?? 'published',
      ...(data.status === 'completed' ? { startedAt: data.departureTime, completedAt: new Date(data.departureTime.getTime() + 30 * 60_000) } : {}),
      stops: { create: corridor },
    },
    include: { stops: true },
  });
}

export async function seed(now = new Date()) {
  const verified = new Date(now.getTime() - 90 * 24 * 3600_000);
  const today = kigaliDayKey(now);
  const tomorrow = addDays(today, 1);
  const yesterday = addDays(today, -1);

  await prisma.place.createMany({ data: KIGALI_PLACES.map((p) => ({ ...p })) });

  const admin = await prisma.user.create({
    data: { phone: SEED_PHONES.admin, name: 'Take Me Home Admin', isAdmin: true, phoneVerifiedAt: verified },
  });

  const claudine = await prisma.user.create({
    data: {
      phone: SEED_PHONES.claudine,
      name: 'Claudine Uwimana',
      gender: 'female',
      homeArea: 'Nyamirambo',
      email: 'claudine@example.rw',
      trustedContactPhone: '+250788100002',
      phoneVerifiedAt: verified,
      emailVerifiedAt: verified,
      idVerifiedAt: verified,
      driverVerifiedAt: verified,
      ratingAvg: 4.8,
      ratingCount: 37,
      createdAt: verified,
      vehicles: {
        create: { make: 'Toyota', model: 'Corolla', plate: 'RAD 123 A', color: 'Silver', seats: 5, isEV: false, photos: [], verifiedAt: verified },
      },
    },
    include: { vehicles: true },
  });

  const aline = await prisma.user.create({
    data: {
      phone: SEED_PHONES.aline,
      name: 'Aline Mukamana',
      gender: 'female',
      homeArea: 'Kanombe',
      phoneVerifiedAt: verified,
      idVerifiedAt: verified,
      driverVerifiedAt: verified,
      ratingAvg: 4.9,
      ratingCount: 52,
      createdAt: verified,
      vehicles: {
        create: { make: 'Toyota', model: 'RAV4', plate: 'RAE 456 B', color: 'White', seats: 5, isEV: false, photos: [], verifiedAt: verified },
      },
    },
    include: { vehicles: true },
  });

  const jeanPaul = await prisma.user.create({
    data: {
      phone: SEED_PHONES.jeanPaul,
      name: 'Jean-Paul Habimana',
      gender: 'male',
      homeArea: 'Remera',
      phoneVerifiedAt: verified,
      driverVerifiedAt: verified,
      ratingAvg: 4.7,
      ratingCount: 21,
      createdAt: verified,
      vehicles: {
        create: { make: 'Hyundai', model: 'Kona Electric', plate: 'RAF 789 C', color: 'Blue', seats: 5, isEV: true, photos: [], verifiedAt: verified },
      },
      verificationRequests: { create: { type: 'id', documentUrl: `/uploads/${await writeSampleId()}` } },
    },
    include: { vehicles: true },
  });

  const grace = await prisma.user.create({
    data: {
      phone: SEED_PHONES.grace,
      name: 'Grace Ingabire',
      gender: 'female',
      homeArea: 'Kimisagara',
      trustedContactPhone: '+250788100005',
      phoneVerifiedAt: verified,
      idVerifiedAt: verified,
      ratingAvg: 4.9,
      ratingCount: 14,
      createdAt: verified,
    },
  });

  const eric = await prisma.user.create({
    data: {
      phone: SEED_PHONES.eric,
      name: 'Eric Nshuti',
      gender: 'male',
      homeArea: 'Remera',
      trustedContactPhone: '+250788100006',
      phoneVerifiedAt: verified,
      ratingAvg: 4.6,
      ratingCount: 8,
      createdAt: verified,
    },
  });

  // Claudine: out in the morning, back in the evening — her two trips for tomorrow.
  const claudineTrip = await createTrip({
    driverId: claudine.id,
    vehicleId: claudine.vehicles[0]!.id,
    departureTime: kigaliDateTime(tomorrow, '07:00'),
    stops: ['nyamirambo', 'kimisagara', 'nyabugogo', 'cbd'],
    seats: 3,
  });
  await createTrip({
    driverId: claudine.id,
    vehicleId: claudine.vehicles[0]!.id,
    departureTime: kigaliDateTime(tomorrow, '17:30'),
    stops: ['cbd', 'nyabugogo', 'kimisagara', 'nyamirambo'],
    seats: 3,
  });

  // Aline: women-only RAV4 from Kanombe.
  await createTrip({
    driverId: aline.id,
    vehicleId: aline.vehicles[0]!.id,
    departureTime: kigaliDateTime(tomorrow, '07:15'),
    stops: ['kanombe', 'giporoso', 'remera', 'kimihurura', 'cbd'],
    seats: 3,
    womenOnly: true,
  });

  // Jean-Paul: EV Kona, recurring on weekdays at 08:00 (dated occurrences for the next week).
  const seriesId = `seed-series-kona`;
  for (const departureTime of occurrencesFor(kigaliDateTime(tomorrow, '08:00'), WEEKDAYS)) {
    await createTrip({
      driverId: jeanPaul.id,
      vehicleId: jeanPaul.vehicles[0]!.id,
      departureTime,
      stops: ['remera', 'kimihurura', 'kacyiru'],
      seats: 3,
      isEV: true,
      recurringDays: WEEKDAYS,
      seriesId,
    });
  }

  // Yesterday's completed Kona trip with Eric — ready to rate on both sides.
  const pastTrip = await createTrip({
    driverId: jeanPaul.id,
    vehicleId: jeanPaul.vehicles[0]!.id,
    departureTime: kigaliDateTime(yesterday, '08:00'),
    stops: ['remera', 'kimihurura', 'kacyiru'],
    seats: 3,
    isEV: true,
    status: 'completed',
  });
  const pastC = computeContribution({ segmentKm: pastTrip.totalKm, seatsOffered: 3, isEV: true });
  const pastRequest = await prisma.joinRequest.create({
    data: {
      tripId: pastTrip.id,
      passengerId: eric.id,
      boardStopId: pastTrip.stops.find((s) => s.order === 0)!.id,
      alightStopId: pastTrip.stops.find((s) => s.order === 2)!.id,
      status: 'accepted',
      segmentKm: pastTrip.totalKm,
      contributionAmount: pastC.costShare,
      bookingFee: pastC.bookingFee,
      createdAt: new Date(kigaliDateTime(yesterday, '06:30')),
      respondedAt: new Date(kigaliDateTime(yesterday, '06:35')),
    },
  });
  const pastPayment = await prisma.payment.create({
    data: {
      joinRequestId: pastRequest.id,
      amount: pastC.total,
      provider: 'mtn_momo',
      providerRef: 'MOMO-SEED-PAST01',
      msisdn: eric.phone,
      status: 'confirmed',
      confirmedAt: kigaliDateTime(yesterday, '06:36'),
    },
  });
  const pastBooking = await prisma.booking.create({
    data: { joinRequestId: pastRequest.id, paymentId: pastPayment.id, tripCode: 'TMH-K7Q2', status: 'completed' },
  });
  await prisma.payout.create({
    data: { tripId: pastTrip.id, driverId: jeanPaul.id, amount: pastC.costShare, provider: 'mtn_momo', providerRef: 'MOMO-PAYOUT-SEED01' },
  });

  // Grace has asked to join Claudine's morning trip — waiting on the driver dashboard.
  const nyabugogo = claudineTrip.stops.find((s) => s.placeId === 'nyabugogo')!;
  const cbd = claudineTrip.stops.find((s) => s.placeId === 'cbd')!;
  const segKm = Math.round((cbd.cumulativeKm - nyabugogo.cumulativeKm) * 10) / 10;
  const graceC = computeContribution({ segmentKm: segKm, seatsOffered: 3, isEV: false });
  await prisma.joinRequest.create({
    data: {
      tripId: claudineTrip.id,
      passengerId: grace.id,
      boardStopId: nyabugogo.id,
      alightStopId: cbd.id,
      segmentKm: segKm,
      contributionAmount: graceC.costShare,
      bookingFee: graceC.bookingFee,
    },
  });

  await prisma.notification.createMany({
    data: [
      {
        userId: claudine.id,
        type: 'join_request',
        payload: { title: 'New request to join', body: `Grace Ingabire wants a seat Nyabugogo → CBD · cost share RWF ${graceC.costShare}.`, href: '/my-trip' },
      },
      {
        userId: eric.id,
        type: 'rate_trip',
        payload: { title: 'You made it home — rate your trip', body: 'How was your ride with Jean-Paul Habimana?', href: `/rate/${pastBooking.id}` },
      },
      {
        userId: jeanPaul.id,
        type: 'rate_passengers',
        payload: { title: 'Trip completed', body: 'Thanks for sharing your ride. Rate your passenger.', href: `/trip/${pastTrip.id}` },
      },
    ],
  });

  return { admin, claudine, aline, jeanPaul, grace, eric, claudineTrip, pastBooking };
}

/** Deletes every row (children first). Used by tests and `pnpm db:reset`. */
export async function wipe() {
  await prisma.$transaction([
    prisma.chatMessage.deleteMany(),
    prisma.rating.deleteMany(),
    prisma.sosEvent.deleteMany(),
    prisma.report.deleteMany(),
    prisma.booking.deleteMany(),
    prisma.payment.deleteMany(),
    prisma.payout.deleteMany(),
    prisma.joinRequest.deleteMany(),
    prisma.tripStop.deleteMany(),
    prisma.trip.deleteMany(),
    prisma.verificationRequest.deleteMany(),
    prisma.vehicle.deleteMany(),
    prisma.notification.deleteMany(),
    prisma.block.deleteMany(),
    prisma.otpChallenge.deleteMany(),
    prisma.devOutbox.deleteMany(),
    prisma.user.deleteMany(),
    prisma.place.deleteMany(),
  ]);
}

export async function seedIfEmpty(): Promise<boolean> {
  if ((await prisma.user.count()) > 0) return false;
  await seed();
  return true;
}
